# Generated by Django 4.2.7 on 2023-11-17 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("padaria", "0002_alter_padaria_horario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="padaria",
            old_name="horario",
            new_name="dia",
        ),
    ]
